language: node_js
node_js:
  - 4

branches:
  only:
    - master

cache:
  bundler: true
  directories:
    - node_modules
    - vendor/bundle

before_install:
  - rvm install 2.2.2
  - npm set progress=false
  - git config --global user.name "ItsJonQ"
  - git config --global user.email "itsjonq@gmail.com"
  - git config --global url.https://github.com/.insteadOf git://github.com/

install:
  - bundle install
  - npm install

before_script:
  - npm install gulp-cli -g

script:
  - gulp deploy
