title: Seed Docs
description: Docs and guidelines for Seed CSS
baseurl: ""
ENV: development
source: ./src

# Build settings
markdown: kramdown

permalink: pretty

exclude:
  - _site
  - .asset-cache
  - .cache
  - .gitignore
  - node_modules
