title: Seed Docs
description: Docs and guidelines for Seed CSS
baseurl: "/seed-docs"
ENV: development
source: ./src
destination: ./seed-docs

# Build settings
markdown: kramdown
highlighter: rouge

permalink: pretty

exclude:
  - _site
  - .asset-cache
  - .cache
  - .gitignore
  - node_modules

collections:
  guides:
    output: true
    permalink: /guide/:path/

defaults:
  -
    scope:
      path: ""
      type: "guides"
    values:
      layout: "guide"

excerpt_separator: <!--more-->
